source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'MercadoPago' do
pod 'Alamofire', '~> 3.3'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
